import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Ironclad Tactical System palette
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-lowest': '#0e0e0e',
        'surface-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-high': '#2a2a2a',
        'surface-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c8c7b8',
        outline: '#919283',
        'outline-variant': '#47483c',
        primary: '#c3cc8c',
        'on-primary': '#2d3404',
        'primary-container': '#4b5320',
        'on-primary-container': '#bdc787',
        secondary: '#ffe2ab',
        'on-secondary': '#402d00',
        'secondary-container': '#ffbf00',
        'on-secondary-container': '#6d5000',
        tertiary: '#abcdcd',
        'on-tertiary': '#143535',
        'tertiary-container': '#345454',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        background: '#131313',
        'on-background': '#e5e2e1',
        // Status colors
        'status-present': '#66ff33',
        'status-leaving': '#f4d35e',
        'status-returning': '#1e4ed8',
        'status-sick': '#f5cac3',
        'status-leave-return': '#c1554f',
        'status-day-trip': '#7aa44f',
        'status-paid': '#ff45c8',
        'status-release': '#1a1a1a',
        'status-release-fg': '#ffffff',
        'status-open': '#4a6b21',
        'status-organizing': '#e08a3c',
        'status-home': '#f3cfc6',
        'status-abroad': '#ed9a3c',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'status-badge': ['14px', { lineHeight: '1', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '16px',
        gutter: '12px',
        'section-gap': '24px',
      },
    },
  },
  plugins: [],
} satisfies Config
